version: '2'
# service configuration for our dockerized Rails app
services:
  db:
    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres:9.6.1
   
    # persist the database between containers by storing it in a volume
    volumes:
      - ../docker-persisted/baton-postgres:/var/lib/postgresql/data

  web:
    # use the Dockerfile next to this file
    build: .
   
    # sources environment variable configuration for our app
    env_file: .env
   
    # rely on the RAILS_ENV value of the host machine
    environment:
      RAILS_ENV: $RAILS_ENV
   
    # makes the app container aware of the DB container
    depends_on:
      - db

    entrypoint: /baton/docker-entry.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/baton
   
    # expose the port we configured Unicorn to bind to
    ports:
      - "3000:3000"